sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3

  # stack
  - ghc: 8.4.4
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.4.4.yaml"
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.6.5.yaml"
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

  # elm
  - language: elm
    cache:
      directories:
      - "$HOME/.npm"
      - "$TRAVIS_BUILD_DIR/frontend/node_modules"

    install:
      - cd frontend/
      - npm install -g create-elm-app
      - npm install
    script:
      - elm-app build
      - elm-app test

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal update
      cabal build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
